# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 15:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20170531_1529'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'Категория товара', 'verbose_name_plural': 'Категория товара'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='type',
            new_name='category',
        ),
    ]
